# Generated by Django 3.0.8 on 2020-07-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200710_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wireframe',
            name='image',
            field=models.ImageField(upload_to='wireframe_images/'),
        ),
    ]
