# Generated by Django 3.0.8 on 2020-07-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200710_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
